class UsernameAlreadyTaken implements Exception {
  static const String message = "Username already taken!";
  UsernameAlreadyTaken();
}